#!/usr/bin/env bash

set -e

cmd=$1

cwd=$(pwd)

# change to directory where script resides for tsx to work
cd "$(dirname $(readlink -f $0))"
npx tsx src/tools/esbuild.ts $cwd $cmd

# change back to directory where script was executed from
cd $cwd
exec bin/$cmd "$@"
